# Generated by Django 5.1.1 on 2024-09-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='education',
            field=models.CharField(choices=[('below_college', '大专以下'), ('college', '大专'), ('bachelor', '本科'), ('master_above', '研究生及以上')], default='大专', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='major_category',
            field=models.CharField(choices=[('it', 'IT'), ('non_it', '非IT')], default='IT', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='major_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('employed', '在职'), ('unemployed', '待业')], default='待业', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='wechat_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesuser',
            name='group_leader',
            field=models.ForeignKey(blank=True, help_text='Assign a group leader to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('group_leader', 'group_leader'), ('admin', 'admin')], default='user', max_length=50),
        ),
    ]
