# Generated by Django 5.1.1 on 2024-09-30 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0002_remove_customer_email_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户列表'},
        ),
        migrations.AlterModelOptions(
            name='salesuser',
            options={'verbose_name': '销售用户', 'verbose_name_plural': '销售用户列表'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='客户描述'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.CharField(choices=[('below_college', '大专以下'), ('college', '大专'), ('bachelor', '本科'), ('master_above', '研究生及以上')], default='大专', max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='major_category',
            field=models.CharField(choices=[('it', 'IT'), ('non_it', '非IT')], default='IT', max_length=10, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='major_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业详细信息'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('employed', '在职'), ('unemployed', '待业')], default='待业', max_length=15, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wechat_id',
            field=models.CharField(default='', max_length=50, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='group_leader',
            field=models.ForeignKey(blank=True, help_text='为该用户分配一个组长.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='组长'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='该用户所属的用户组', related_name='salesuser_set', to='auth.group', verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('group_leader', '组长'), ('admin', '管理员')], default='user', max_length=50, verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='该用户拥有的特定权限', related_name='salesuser_set', to='auth.permission', verbose_name='用户权限'),
        ),
    ]
