# Generated by Django 5.1.1 on 2024-10-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_options_alter_salesuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.CharField(choices=[('below_college', '大专以下'), ('college', '大专'), ('bachelor', '本科'), ('master_above', '研究生及以上')], default='college', max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='major_category',
            field=models.CharField(choices=[('it', 'IT'), ('non_it', '非IT')], default='it', max_length=10, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('employed', '在职'), ('unemployed', '待业')], default='unemployed', max_length=15, verbose_name='状态'),
        ),
    ]
